version: "3.8"

services:
  backend:
    build: ./backend
    container_name: face-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-falling-salad-adm7k1ia-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_Ly1HkrAGRV5I
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

  frontend:
    build:
      context: ./frontend
    container_name: face-frontend
    ports:
      - "3000:80"
